POST http://localhost:3001/api/persons/
content-type: application/json

{
    "name": "Jim",
    "number": "1234"
}

###
POST http://localhost:3001/api/persons/
content-type: application/json

{
    "name": "Jim"
}

###
POST http://localhost:3001/api/persons/
content-type: application/json

{
    "name": "Arto Hellas",
    "number": "1234"
}